@api = http://localhost:4000


### AUTHENTICATED
### USER [ADMIN]
POST {{api}}/auth/signin
Content-Type: application/json

{
    "userName": "Paulo",
    "password": "Pc3rtiblepass%"
    
}
### USER [NORMAL]

POST {{api}}/auth/signin
Content-Type: application/json

{
    "userName": "wolf",
    "password": "3rriblepass%asdA"
    
}


### USER [NORMAL]

POST {{api}}/auth/signin
Content-Type: application/json

{
    "userName": "unknown user",
    "password": "3rriblepass%asdA"
    
}