@api = http://localhost:4000


GET {{api}}/users

###

GET {{api}}/users/61941fa4bccf81dedd247514

### Create a user ADMIN
POST {{api}}/users
Content-Type: application/json

{
    "userName": "Paulo",
    "email": "paulo@gmail.com",
    "password": "Pc3rtiblepass%",
    "firstName": "Paulo",
    "lastName": "Rojas",
    "avatar": "",
    "roles": ["admin"]
}


### Create a user NORMAL
POST {{api}}/users
Content-Type: application/json

{
    "userName": "wolf",
    "email": "wolf@gmail.com",
    "password": "3rriblepass%asdA",
    "firstName": "Paulo",
    "lastName": "Rojas",
    "avatar": ""
}

### Create a user NORMAL
POST {{api}}/users
Content-Type: application/json

{
    "userName": "unknown user",
    "email": "unknown_user@gmail.com",
    "password": "3rriblepass%asdA",
    "firstName": "Paulo",
    "lastName": "Rojas",
    "avatar": ""
}